## Context

This change was generated by the spectra-exporter adapter from a codebase scan.
The connection map identifies UI components that need to be wired to API endpoints.
Framework detected: `{{framework}}`.

## Architecture

### Connection Map

{{connections_table}}

### API Contracts

{{api_contracts}}

### UI Component Bindings

{{ui_bindings}}

## Decisions

### Decision: Use existing framework routing

- **Context**: All API endpoints belong to the detected framework (`{{framework}}`).
- **Decision**: Implement new endpoints following the existing routing conventions in the project.
- **Consequences**: Consistent with codebase conventions; no new framework introduced.

## Constraints

- Each new endpoint MUST validate request parameters before processing.
- UI components MUST call the endpoint via the project's existing HTTP client abstraction.
- No direct `fetch` calls; use the established service/hook pattern.
